### PR TITLE
+ add optional to-parameter to get_metric_history()

### PR DESCRIPTION
**Pull request by stephanpoetschner**
`R.get_metric_history()` handles an options `since` parameter.
When trying to get data from a specific period in the past, an optional `to` parameter would be helpful, to restrict the time-range to a specific interval.

* This pull-request adds the optional parameter `to`.
* This code introduces backwards incompatibility for existing code that uses `get_metric_history()` with unnamed-arguments (e.g. `client.get_metric_history(slugs, since, 'daily')`)

### CODE REVIEW

**Comment by stephanpoetschner** [comment]
The above travis status message is misleading :)

Tests on all environments pass, except for Python 3.4 / Django 1.7.6
https://travis-ci.org/bradmontgomery/django-redis-metrics/jobs/124198538

> No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
> The build has been terminated

**Comment by bradmontgomery** [comment]
Hi @stephanpoetschner, thanks for this work. I'll try to look over it thoroughly within the next day or 2, but I think it sounds like a good idea.

**Comment by bradmontgomery** [comment]
@stephanpoetschner Thanks again for this work. Version 1.4.0 is now on pypi.

**Comment by stephanpoetschner** [comment]
@bradmontgomery 
Thanks a lot for your great software and the fast response!
Really appreciate your effort.

**Pull request merged**
